### ISSUE TITLE
TypeError: main() missing 3 required positional

### ISSUE THREAD

**Issue by deeperdragon** [Deevoluation/ALPR#28]
Enter the name of the video: 1.mp4
Hello, 
I have a error when run Start.py
---------------------------------
total frames = :  304
total frames generated = :  5

time taken = 3.8460967540740967
Traceback (most recent call last):
  File "Start.py", line 29, in <module>
    pred, img = Launch.main(f)
TypeError: main() missing 3 required positional arguments: 'save_intermediate', 'output_folder', and 'showSteps'
------------------------------------------
How I can resolve it.
Thank you very muh

**Comment by Saqhas** [comment]
Thank you for reporting this issue.
There was some problem with the mastet code.
We have fixed it.
Please pull the latest code and try again.
In case of an issue please report here.

**Comment by deeperdragon** [comment]
Thank you very much for your reply.
Yes this error is fixed but I have a another error ( here is the screenshot)
![errorLP](https://user-images.githubusercontent.com/40325308/73614794-91e7fc00-4602-11ea-8820-daa613e60eb3.png)

Thanks a lot

**Comment by Saqhas** [comment]
This error should not come. 
It says that the plate_detector folder is not there.
But it is there in the repository.
Are you running the code in the repo folder only or some where else.

If you are trying to run it somewhere else then you will need to all the folders there as well.

If still the problem remains then please contact here.

Thank you

**Comment by deeperdragon** [comment]
Hello,
Yes this error not resolved yet :( but the frozen file exist in plate_detector. here is a screenshot : 
![frozen](https://user-images.githubusercontent.com/40325308/73661797-fb1b4e00-469a-11ea-848b-2fa5d6f1417e.png)

But when I run the Launch.py -i 1.jpg for testing  an image, the code is correct and I have in terminal the license plate and here is the screenshot
![LP_error2](https://user-images.githubusercontent.com/40325308/73662005-5ea57b80-469b-11ea-9258-be39677c7742.png)

After that I will test your code the same error obtained again :(  
![LP_error3](https://user-images.githubusercontent.com/40325308/73662107-85fc4880-469b-11ea-9acc-9f35e9013466.png)

Please Help me for the video code.
Thanks a lot

**Comment by deeperdragon** [comment]
Thank you for collaborate, 
I resolve this error :) 

The process of LP detection is good but the process for Plate recognition is not perfectly (a many error ).

How I optimized the LP recognition ? I retrained the model ? 

Thank you

**Comment by Saqhas** [comment]
The plate number recognition is tough because it has lots of variants in it.
Retraining the model might not help, because it just recognizes characters.
Just give us sometime. We have been working extensively on this and soon the  better approach will be updated in the github.

Thank you

**Comment by deeperdragon** [comment]
okay, Thank you very much
